### PR TITLE
Add project badges

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by sinoroc** [comment]
Thanks for this!

In general I am not into badges. I find them misleading, for example they often do not represent the state of the currently visible branch. You could have the CI on the main branch failing, but the release branch is perfectly fine and so on.

In my eyes, the only meaningful one here is the one simply pointing to _PyPI_, but I already tried to place links to _PyPI_ in prominent places.

I will think about it.  Thanks.

**Comment by johnthagen** [comment]
Yes, feel free to close if you don't feel this is good. I just find badges as a nice way to quickly link to things, see that a project has CI, etc.

**Comment by sinoroc** [comment]
I agree. But especially in that case it is quite misleading. I do have a CI that passes, but there is no actual test, no code coverage. I mostly do just linting. So it might not be a meaningful signal.

I am open to brainstorm some ideas to somehow show an accurate representation of the project's. But maybe not with badges in the Readme. I think maybe GitLab solves it a bit better, the badges are in the repository settings, not in the readme, so they can be synched with the currently visible branch.

**Comment by johnthagen** [comment]
Sounds good, I'll go ahead and close this PR.

**Pull request closed without merging**
