### PR TITLE
Fix TypeError under Python 3.5

### LINKED ISSUE #3: "TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>" with Python 3.5
As both `tox` and `poetry` support Python 3.5 (for now), I presume this plugin should, as well. Currently, this error results when it executes under Python 3.5:
```
$ tox
.tox create: /Users/mikenerone/dev/threatq/pynoceros/.tox/.tox
.tox installdeps: poetry-core>=1.0.0a5, tox-poetry-dev-dependencies, tox >= 3.20.0
Traceback (most recent call last):
  File "/Users/mikenerone/.pyenv/versions/3.5.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mikenerone/.pyenv/versions/3.5.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox/__main__.py", line 4, in <module>
    tox.cmdline()
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox/session/__init__.py", line 65, in main
    config = load_config(args)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox/session/__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox/config/__init__.py", line 281, in parseconfig
    pm.hook.tox_configure(config=config)  # post process config object
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox_poetry_dev_dependencies/_hooks.py", line 37, in tox_configure
    requirements = _get_dev_requirements(config.setupdir)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/tox_poetry_dev_dependencies/_hooks.py", line 56, in _get_dev_requirements
    poetry_ = poetry_factory.create_poetry(project_root_path)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/poetry/core/factory.py", line 23, in create_poetry
    poetry_file = self.locate(cwd)
  File "/Users/mikenerone/dev/threatq/pynoceros/.tox/.tox/lib/python3.5/site-packages/poetry/core/factory.py", line 197, in locate
    candidates = [Path(cwd)]
  File "/Users/mikenerone/.pyenv/versions/3.5.5/lib/python3.5/pathlib.py", line 969, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/mikenerone/.pyenv/versions/3.5.5/lib/python3.5/pathlib.py", line 651, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/mikenerone/.pyenv/versions/3.5.5/lib/python3.5/pathlib.py", line 643, in _parse_args
    % type(a))
TypeError: argument should be a path or str object, not <class 'py._path.local.LocalPath'>
```
I'll submit a trivial pull request to resolve this shortly.

### PR DESCRIPTION
**Pull request by mikenerone**
Fixes #3

### CODE REVIEW

**Comment by sinoroc** [comment]
Theoretically we should adjust the CI, etc. so that we test against Python 3.5 as well. But from a quick first try, seems like it would bring other breakages (with _pytest-yapf3_). But since the code change is so small maybe we could simply take the change without advertising Python 3.5 compatibility. It would be compatible by coincidence.

**Comment by sinoroc** [comment]
Since I host the code on both _GitHub_ and _GitLab_ (and who knows where the code will land later on), I want to have elements of the commit messages that refer to a specific platform prefixed accordingly. It makes things clearer anyway. Something like:

```
Fix TypeError under Python 3.5

GitHub: fixes #3
```

Would you mind doing that?

**Comment by mikenerone** [comment]
Of course, done. :)

**Comment by mikenerone** [comment]
> But from a quick first try, seems like it would bring other breakages (with _pytest-yapf3_).

Perhaps you could exclude the yapf checks for the 3.5 run. Side note: I look forward to not using 3.5 myself and not caring about this. :D But for the moment, you know, constraints.

**Comment by sinoroc** [comment]
> Of course, done. :)

Thanks.

> Perhaps you could exclude the yapf checks for the 3.5 run.

Yes. I have been meaning to revamp the whole thing for a while now, since there is no reason to do the whole linting, typing, formatting, etc. for each Python version (sometimes they even contradict each other). Once it's done, I will think about activating Python 3.5 in the CI.

> I look forward to not using 3.5 myself and not caring about this. :D But for the moment, you know, constraints.

I get it. If it is truly needed then I will try to get the change in and publish a new release quickly.

**Comment by mikenerone** [comment]
Many thanks!

**Pull request merged**
